### PR TITLE
Update angular module reference

### PR DESCRIPTION
**Pull request by kenhowardpdx**
@NathanWalker A minor update to make these snippets compatible with the latest RC.

### CODE REVIEW

**Comment by NathanWalker** [comment]
Thanks Ken! I'll merge and publish tomorrow.

**Comment by jmarchello** [comment]
@NathanWalker any chance you could merge this in? It would be very helpful. Thanks!

**Comment by NathanWalker** [comment]
Ah yes! Lost track of this one, thank you @kenhowardpdx !! And for the ping @jmarchello 
I'll push a release in just a moment with this fix.

**Comment by NathanWalker** [comment]
`1.1.0` released now!

**Pull request merged**
